name: Backend Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  AWS_REGION: us-east-1

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        run: pip install pipenv

      - name: Cache Python Dependencies
        id: CachingData
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: deps-python-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install Project Dependencies
        run: 
          pipenv install --dev
          pipenv install flake8

      - name: Run Lint
        run: pipenv run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        run: pip install pipenv

      - name: Cache Python Dependencies
        id: CachingData
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: deps-python-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        run: 
          pipenv install --dev
          pipenv install flake8

      - name: Run Tests
        run: pipenv run test
        continue-on-error: false

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint,test]
    defaults:
        run:
          working-directory: starter/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Pushes the docker image to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: backend
          IMAGE_TAG: ${{ github.sha }}
          REACT_APP_MOVIE_API_URL: ${{ vars.REACT_APP_MOVIE_API_URL }}      
        run:  |
          docker build --build-arg=REACT_APP_MOVIE_API_URL="http://$REACT_APP_MOVIE_API_URL" -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Setup Kubeconfig Auth
        run: |
          aws eks update-kubeconfig --name cluster --region us-east-1
          kubectl get svc
          kubectl config view
      - name: Run init.sh
        run:  |
          chmod +x init.sh 
          ./init.sh || true
          kubectl config view
        working-directory: setup

      - name: Deploys the application using kubectl to the eks cluster
        run:  |
          cd starter/backend/k8s
          kustomize edit set image backend=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/backend:latest
          kustomize build | kubectl apply -f -
       
