name: Frontend CI Workflow
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: Setup up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0

      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
        
      - name: Install Project Dependencies
        run: npm ci

      - name: Now Running Lint
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: Setup up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0

      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
        
      - name: Install Project Dependencies
        run: npm ci

      - name: Run Test
        run: npm run test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint,test]
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: Build Image
        run: docker build .
